spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: secretKey
  expiration: 3600000
ongoing.queue:
  capacity: 100
